== Monsters (A)

=== Aboleth

_Large aberration, lawful evil_

*Armor Class* 17 (natural armor)

*Hit Points* 135 (18d10 + 36)

*Speed* 10 ft., swim 40 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|21 (+5) |9 (−1) |15 (+2) |18 (+4) |15 (+2) |18 (+4)
|===

*Saving Throws* Con +6, Int +8, Wis +6

*Skills* History +12, Perception +10

*Senses* darkvision 120 ft., passive Perception 20

*Languages* Deep Speech, telepathy 120 ft.

*Challenge* 10 (5,900 XP)

*Amphibious.* The aboleth can breathe air and water.

*Mucous Cloud.* While underwater, the aboleth is surrounded by
transformative mucus. A creature that touches the aboleth or that hits
it with a melee attack while within 5 feet of it must make a DC 14
Constitution saving throw. On a failure, the creature is diseased for
1d4 hours. The diseased creature can breathe only underwater.

*Probing Telepathy.* If a creature communicates telepathically with the
aboleth, the aboleth learns the creature’s greatest desires if the
aboleth can see the creature.

==== Actions

*Multiattack.* The aboleth makes three tentacle attacks.

*Tentacle.* _Melee Weapon Attack:_ +9 to hit, reach 10 ft., one target.
_Hit:_ 12 (2d6 + 5) bludgeoning damage. If the target is a creature, it
must succeed on a DC 14 Constitution saving throw or become diseased.
The disease has no effect for 1 minute and can be removed by any magic
that cures disease. After 1 minute, the diseased creature’s skin becomes
translucent and slimy, the creature can’t regain hit points unless it is
underwater, and the disease can be removed only by _heal_ or another
disease-­‐curing spell of 6th level or higher. When the creature is
outside a body of water, it takes 6 (1d12) acid damage every 10 minutes
unless moisture is applied to the skin before 10 minutes have passed.

*Tail.* _Melee Weapon Attack:_ +9 to hit, reach 10 ft. one target.
_Hit:_ 15 (3d6 + 5) bludgeoning damage.

*Enslave (3/Day)*. The aboleth targets one creature it can see within 30
feet of it. The target must succeed on a DC 14 Wisdom saving throw or be
magically charmed by the aboleth until the aboleth dies or until it is
on a different plane of existence from the target. The charmed target is
under the aboleth’s control and can't take actions, and the aboleth and
the target can communicate telepathically with each other over any
distance.

Whenever the charmed target takes damage, the target can repeat the
saving throw. On a success, the effect ends. No more than once every 24
hours, the target can also repeat the saving throw when it is at least 1
mile away from the aboleth.

==== Legendary Actions

The aboleth can take 3 legendary actions, choosing from the options
below. Only one legendary action option can be used at a time and only
at the end of another creature’s turn. The aboleth regains spent
legendary actions at the start of its turn.

*Detect.* The aboleth makes a Wisdom (Perception) check.

*Tail Swipe.* The aboleth makes one *Tail Attack.*

*Psychic Drain (Costs 2 Actions).*. One creature charmed by the aboleth
takes 10 (3d6) psychic damage, and the aboleth regains hit points equal
to the damage the creature takes.

=== Angels

==== Deva

_Medium celestial, lawful good_

*Armor Class* 17 (natural armor)

*Hit Points* 136 (16d8 + 64)

*Speed* 30 ft., fly 90 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|18 (+4) |18 (+4) |18 (+4) |17 (+3) |20 (+5) |20 (+5)
|===

*Saving Throws* Wis +9, Cha +9

*Skills* Insight +9, Perception +9

*Damage Resistances* radiant; bludgeoning, piercing, and slashing from
nonmagical attacks

*Condition Immunities* charmed, exhaustion, frightened

*Senses* darkvision 120 ft., passive Perception 19

*Languages* all, telepathy 120 ft.

*Challenge* 10 (5,900 XP)

*Angelic Weapons.* The deva’s weapon attacks are magical. When the deva
hits with any weapon, the weapon deals an extra 4d8 radiant damage
(included in the attack).

*Innate Spellcasting* The deva’s spellcasting ability is Charisma (spell
save DC 17). The deva can innately cast the following spells, requiring
only verbal components:

At will: _detect evil and good_

1/day each: _commune_, _raise dead_

*Magic Resistance.* The deva has advantage on saving throws against
spells and other magical effects.

===== Actions

*Multiattack.* The deva makes two melee attacks.

*Mace.* _Melee Weapon Attack:_ +8 to hit, reach 5 ft., one target.
_Hit:_ 7 (1d6 + 4) bludgeoning damage plus 18 (4d8) radiant damage.

*Healing Touch (3/Day).* The deva touches another creature. The target
magically regains 20 (4d8 + 2) hit points and is freed from any curse,
disease, poison, blindness, or deafness.

*Change Shape.* The deva magically polymorphs into a humanoid or beast
that has a challenge rating equal to or less than its own, or back into
its true form. It reverts to its true form if it dies. Any equipment it
is wearing or carrying is absorbed or borne by the new form (the deva’s
choice).

In a new form, the deva retains its game statistics and ability to
speak, but its AC, movement modes, Strength, Dexterity, and special
senses are replaced by those of the new form, and it gains any
statistics and capabilities (except class features, legendary actions,
and lair actions) that the new form has but that it lacks.

==== Planetar

_Large celestial, lawful good_

*Armor Class* 19 (natural armor)

*Hit Points* 200 (16d10 + 112)

*Speed* 40 ft., fly 120 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|24 (+7) |20 (+5) |24 (+7) |19 (+4) |22 (+6) |25 (+7)
|===

*Saving Throws* Con +12, Wis +11, Cha +12

*Skills* Perception +11

*Damage Resistances* radiant; bludgeoning, piercing, and slashing from
nonmagical attacks

*Condition Immunities* charmed, exhaustion, frightened

*Senses* truesight 120 ft., passive Perception 21

*Languages* all, telepathy 120 ft.

*Challenge* 16 (15,000 XP)

*Angelic Weapons.* The planetar’s weapon attacks are magical. When the
planetar hits with any weapon, the weapon deals an extra 5d8 radiant
damage (included in the attack).

*Divine Awareness.* The planetar knows if it hears a lie.

*Innate Spellcasting* The planetar’s spellcasting ability is Charisma
(spell save DC 20). The planetar can innately cast the following spells,
requiring no material components:

At will: _detect evil and good_, _invisibility_ (self only)

3/day each: _blade barrier_, _dispel evil and good_, _flamestrike_,
_raise dead_

1/day each: _commune_, _control weather_, _insect plague_

*Magic Resistance.* The planetar has advantage on saving throws against
spells and other magical effects.

===== Actions

*Multiattack.* The planetar makes two melee attacks.

*Greatsword.* _Melee Weapon Attack:_ +12 to hit, reach 5 ft., one
target. _Hit:_ 21 (4d6 + 7) slashing damage plus 22 (5d8) radiant
damage.

*Healing Touch (4/Day).* The planetar touches another creature. The
target magically regains 30 (6d8 + 3) hit points and is freed from any
curse, disease, poison, blindness, or deafness.

==== Solar

_Large celestial, lawful good_

*Armor Class* 21 (natural armor)

*Hit Points* 243 (18d10 + 144)

*Speed* 50 ft., fly 150 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|26 (+8) |22 (+6) |26 (+8) |25 (+7) |25 (+7) |30 (+10)
|===

*Saving Throws* Int +14, Wis +14, Cha +17

*Skills* Perception +14

*Damage Resistances* radiant; bludgeoning, piercing, and slashing from
nonmagical attacks

*Damage Immunities* necrotic, poison

*Condition Immunities* charmed, exhaustion, frightened, poisoned

*Senses* truesight 120 ft., passive Perception 24

*Languages* all, telepathy 120 ft.

*Challenge* 21 (33,000 XP)

*Angelic Weapons.* The solar’s weapon attacks are magical. When the
solar hits with any weapon, the weapon deals an extra 6d8 radiant damage
(included in the attack).

*Divine Awareness.* The solar knows if it hears a lie.

*Innate Spellcasting* The solar’s spellcasting ability is Charisma
(spell save DC 25). It can innately cast the following spells, requiring
no material components:

At will: _detect evil and good_, _invisibility_ (self only)

3/day each: _blade barrier_, _dispel evil and good_, _resurrection_

1/day each: _commune_, _control weather_

*Magic Resistance.* The solar has advantage on saving throws against
spells and other magical effects.

===== Actions

*Multiattack.* The solar makes two greatsword attacks.

*Greatsword.* _Melee Weapon Attack:_ +15 to hit, reach 5 ft., one
target. _Hit:_ 22 (4d6 + 8) slashing damage plus 27 (6d8) radiant
damage.

*Slaying Longbow.* Ranged _Weapon Attack:_ +13 to hit, range 150/600
ft., one target. _Hit:_ 15 (2d8 + 6) piercing damage plus 27 (6d8)
radiant damage. If the target is a creature that has 100 hit points or
fewer, it must succeed on a DC 15 Constitution saving throw or die.

*Flying Sword.* The solar releases its greatsword to hover magically in
an unoccupied space within 5 feet of it. If the solar can see the sword,
the solar can mentally command it as a bonus action to fly up to 50 feet
and either make one attack against a target or return to the solar’s
hands. If the hovering sword is targeted by any effect, the solar is
considered to be holding it. The hovering sword falls if the solar dies.

*Healing Touch (4/Day).* The solar touches another creature. The target
magically regains 40 (8d8 + 4) hit points and is freed from any curse,
disease, poison, blindness, or deafness.

===== Legendary Actions

The solar can take 3 legendary actions, choosing from the options below.
Only one legendary action option can be used at a time and only at the
end of another creature’s turn. The solar regains spent legendary
actions at the start of its turn.

*Teleport.* The solar magically teleports, along with any equipment it
is wearing or carrying, up to 120 feet to an unoccupied space it can
see.

*Searing Burst (Costs 2 Actions).* The solar emits magical, divine
energy. Each creature of its choice in a 10-­‐foot radius must make a DC
23 Dexterity saving throw, taking 14 (4d6) fire damage plus 14 (4d6)
radiant damage on a failed save, or half as much damage on a successful
one.

*Blinding Gaze (Costs 3 Actions).* The solar targets one creature it can
see within 30 feet of it. If the target can see it, the target must
succeed on a DC 15 Constitution saving throw or be blinded until magic
such as the _lesser restoration_ spell removes the blindness.

=== Animated Objects

==== Animated Armor

_Medium construct, unaligned_

*Armor Class* 18 (natural armor)

*Hit Points* 33 (6d8 + 6)

*Speed* 25 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|14 (+2) |11 (+0) |13 (+1) |1 (−5) |3 (−4) |1 (−5)
|===

*Damage Immunities* poison, psychic

*Condition Immunities* blinded, charmed, deafened, exhaustion,
frightened, paralyzed, petrified, poisoned

*Senses* blindsight 60 ft. (blind beyond this radius), passive
Perception 6

*Languages* —

*Challenge* 1 (200 XP)

*Antimagic Susceptibility.* The armor is incapacitated while in the area
of an _antimagic field._ If targeted by _dispel magic_, the armor must
succeed on a Constitution saving throw against the caster’s spell save
DC or fall unconscious for 1 minute.

*False Appearance.* While the armor remains motionless, it is
indistinguishable from a normal suit of armor.

===== Actions

*Multiattack.* The armor makes two melee attacks.

*Slam.* _Melee Weapon Attack:_ +4 to hit, reach 5 ft., one target.
_Hit:_ 5 (1d6 + 2) bludgeoning damage.

==== Flying Sword

_Small construct, unaligned_

*Armor Class* 17 (natural armor)

*Hit Points* 17 (5d6)

*Speed* 0 ft., fly 50 ft. (hover)

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|12 (+1) |15 (+2) |11 (+0) |1 (−5) |5 (−3) |1 (−5)
|===

*Saving Throws* Dex +4

*Damage Immunities* poison, psychic

*Condition Immunities* blinded, charmed, deafened, frightened,
paralyzed, petrified, poisoned

*Senses* blindsight 60 ft. (blind beyond this radius), passive
Perception 7

*Languages* —

*Challenge* ¼ (50 XP)

*Antimagic Susceptibility.* The sword is incapacitated while in the area
of an _antimagic field._ If targeted by _dispel magic_, the sword must
succeed on a Constitution saving throw against the caster’s spell save
DC or fall unconscious for 1 minute.

*False Appearance.* While the sword remains motionless and isn’t flying,
it is indistinguishable from a normal sword.

===== Actions

*Longsword.* _Melee Weapon Attack:_ +3 to hit, reach 5 ft., one target.
_Hit:_ 5 (1d8 + 1) slashing damage.

==== Rug of Smothering

_Large construct, unaligned_

*Armor Class* 12

*Hit Points* 33 (6d10)

*Speed* 10 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|17 (+3) |14 (+2) |10 (+0) |1 (−5) |3 (−4) |1 (−5)
|===

*Damage Immunities* poison, psychic

*Condition Immunities* blinded, charmed, deafened, frightened,
paralyzed, petrified, poisoned

*Senses* blindsight 60 ft. (blind beyond this radius), passive
Perception 6

*Languages* —

*Challenge* 2 (450 XP)

*Antimagic Susceptibility.* The rug is incapacitated while in the area
of an _antimagic field._ If targeted by _dispel magic_, the rug must
succeed on a Constitution saving throw against the caster’s spell save
DC or fall unconscious for 1 minute.

*Damage Transfer.* While it is grappling a creature, the rug takes only
half the damage dealt to it, and the creature grappled by the rug takes
the other half.

*False Appearance.* While the rug remains motionless, it is
indistinguishable from a normal rug.

===== Actions

*Smother.* _Melee Weapon Attack:_ +5 to hit, reach 5 ft., one Medium or
smaller creature. _Hit:_ The creature is grappled (escape DC 13). Until
this grapple ends, the target is restrained, blinded, and at risk of
suffocating, and the rug can’t smother another target. In addition, at
the start of each of the target’s turns, the target takes 10 (2d6 + 3)
bludgeoning damage.

==== Ankheg

_Large monstrosity, unaligned_

*Armor Class* 14 (natural armor), 11 while prone

*Hit Points* 39 (6d10 + 6)

*Speed* 30 ft., burrow 10 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|17 (+3) |11 (+0) |13 (+1) |1 (−5) |13 (+1) |6 (−2)
|===

*Senses* darkvision 60 ft., tremorsense 60 ft., passive Perception 11

*Languages* —

*Challenge* 2 (450 XP)

===== Actions

*Bite.* _Melee Weapon Attack:_ +5 to hit, reach 5 ft., one target.
_Hit:_ 10 (2d6 + 3) slashing damage plus 3 (1d6) acid damage. If the
target is a Large or smaller creature, it is grappled (escape DC 13).
Until this grapple ends, the ankheg can bite only the grappled creature
and has advantage on attack rolls to do so.

*Acid Spray (Recharge 6).* The Ankheg spits acid in a line that is 30
feet long and 5 feet wide, provided that it has no creature grappled.
Each creature in that line must make a DC 13 Dexterity saving throw,
taking 10 (3d6) acid damage on a failed save, or half as much damage on
a successful one.

==== Azer

_Medium elemental, lawful neutral_

*Armor Class* 17 (natural armor, shield)

*Hit Points* 39 (6d8 + 12)

*Speed* 30 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|17 (+3) |12 (+1) |15 (+2) |12 (+1) |13 (+1) |10 (+0)
|===

*Saving Throws* Con +4

*Damage Immunities* fire, poison

*Condition Immunities* poisoned

*Senses* passive Perception 11

*Languages* Ignan

*Challenge* 2 (450 XP)

*Heated Body.* A creature that touches the azer or hits it with a melee
attack while within 5 feet of it takes 5 (1d10) fire damage.

*Heated Weapons.* When the azer hits with a metal melee weapon, it deals
an extra 3 (1d6) fire damage (included in the attack).

*Illumination.* The azer sheds bright light in a 10-­‐foot radius and
dim light for an additional 10 feet.

===== Actions

*Warhammer.* _Melee Weapon Attack:_ +5 to hit, reach 5 ft., one target.
_Hit:_ 7 (1d8 + 3) bludgeoning damage, or 8 (1d10 + 3) bludgeoning
damage if used with two hands to make a melee attack, plus 3 (1d6) fire
damage.
