== Monsters (N)

=== Nagas

==== Guardian Naga

_Large monstrosity, lawful good_

*Armor Class* 18 (natural armor)

*Hit Points* 127 (15d10 + 45)

*Speed* 40 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|19 (+4) |18 (+4) |16 (+3) |16 (+3) |19 (+4) |18 (+4)
|===

*Saving Throws* Dex +8, Con +7, Int +7, Wis +8, Cha +8

*Damage Immunities* poison

*Condition Immunities* charmed, poisoned

*Senses* darkvision 60 ft., passive Perception 14

*Languages* Celestial, Common

*Challenge* 10 (5,900 XP)

*Rejuvenation.* If it dies, the naga returns to life in 1d6 days and
regains all its hit points. Only a _wish_ spell can prevent this trait
from functioning.

*Spellcasting.* The naga is an 11th-­‐level spellcaster. Its
spellcasting ability is Wisdom (spell save DC 16, +8 to hit with spell
attacks), and it needs only verbal components to cast its spells. It has
the following cleric spells prepared:

Cantrips (at will): _mending_, _sacred flame_, _thaumaturgy_

1st level (4 slots): _command_, _cure wounds_, _shield of faith_

2nd level (3 slots): _calm emotions_, _hold person_

3rd level (3 slots): _bestow curse_, _clairvoyance_

4th level (3 slots): _banishment_, _freedom of movement_

5th level (2 slots): _flame strike_, _geas_

6th level (1 slot): _true seeing_

===== Actions

*Bite.* _Melee Weapon Attack:_ +8 to hit, reach 10 ft., one creature.
_Hit:_ 8 (1d8 + 4) piercing damage, and the target must make a DC 15
Constitution saving throw, taking 45 (10d8) poison damage on a failed
save, or half as much damage on a successful one.

*Spit Poison.* _Ranged Weapon Attack:_ +8 to hit, range 15/30 ft., one
creature. _Hit:_ The target must make a DC 15 Constitution saving throw,
taking 45 (10d8) poison damage on a failed save, or half as much damage
on a successful one.

==== Spirit Naga

_Large monstrosity, chaotic evil_

*Armor Class* 15 (natural armor)

*Hit Points* 75 (10d10 + 20)

*Speed* 40 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|18 (+4) |17 (+3) |14 (+2) |16 (+3) |15 (+2) |16 (+3)
|===

*Saving Throws* Dex +6, Con +5, Wis +5, Cha +6

*Damage Immunities* poison

*Condition Immunities* charmed, poisoned

*Senses* darkvision 60 ft., passive Perception 12

*Languages* Abyssal, Common

*Challenge* 8 (3,900 XP)

*Rejuvenation.* If it dies, the naga returns to life in 1d6 days and
regains all its hit points. Only a _wish_ spell can prevent this trait
from functioning.

*Spellcasting.* The naga is a 10th-­‐level spellcaster. Its spellcasting
ability is Intelligence (spell save DC 14, +6 to hit with spell
attacks), and it needs only verbal components to cast its spells. It has
the following wizard spells prepared:

Cantrips (at will): _mage hand_, _minor illusion_, _ray of frost_

1st level (4 slots): _charm person_, _detect magic_, _sleep_

2nd level (3 slots): _detect thoughts_, _hold person_

3rd level (3 slots): _lightning bolt_, _water breathing_

4th level (3 slots): _blight_, _dimension door_

5th level (2 slots): _dominate person_

===== Actions

*Bite.* _Melee Weapon Attack:_ +7 to hit, reach 10 ft., one creature.
_Hit:_ 7 (1d6 + 4) piercing damage, and the target must make a DC 13
Constitution saving throw, taking 31 (7d8) poison damage on a failed
save, or half as much damage on a successful one.

==== Nightmare

_Large fiend, neutral evil_

*Armor Class* 13 (natural armor)

*Hit Points* 68 (8d10 + 24)

*Speed* 60 ft., fly 90 ft.

[cols=",,,,,",options="header",]
|===
|STR |DEX |CON |INT |WIS |CHA
|18 (+4) |15 (+2) |16 (+3) |10 (+0) |13 (+1) |15 (+2)
|===

*Damage Immunities* fire

*Senses* passive Perception 11

*Languages* understands Abyssal, Common, and Infernal but can’t speak

*Challenge* 3 (700 XP)

*Confer Fire Resistance.* The nightmare can grant resistance to fire
damage to anyone riding it.

*Illumination.* The nightmare sheds bright light in a 10-­‐ foot radius
and dim light for an additional 10 feet.

===== Actions

*Hooves.* _Melee Weapon Attack:_ +6 to hit, reach 5 ft., one target.
_Hit:_ 13 (2d8 + 4) bludgeoning damage plus 7 (2d6) fire damage.

*Ethereal Stride.* The nightmare and up to three willing creatures
within 5 feet of it magically enter the Ethereal Plane from the Material
Plane, or vice versa.
